# Generated by Django 6.0.2 on 2026-02-13 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_completed_task_is_archived_remove_task_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', 'is_archived', '-updated_at']},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'is_archived', 'status'], name='Task_task_owner_i_06a801_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner'], name='Task_task_owner_i_77907b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='Task_task_due_dat_f0d3d7_idx'),
        ),
    ]
